{
    id:3.1 ,
    assetType:"Aplicativos",
    securityFunction:"Detectar",
    titulo: "Funcionamento de ferramentas automatizadas de escaneamento de vulnerabilidades" ,
    description:"Utilize uma automação de conteúdo de segurança atualizada Verificação de vulnerabilidade compatível com protocolo (SCAP) ferramenta para verificar automaticamente todos os sistemas no rede em uma base semanal ou mais frequente para identificar todas as vulnerabilidades potenciais no sistemas da organização.",
    quest: quest,
},
{
    id:3.2 ,
    assetType:"Aplicativos",
    securityFunction:"Detectar",
    titulo: "Execução de escaneamento de vulnerabilidade autenticada" ,
    description:"Executar verificação de vulnerabilidade autenticada com agentes rodando localmente em cada sistema ou com scanners remotos que são configurados com elevada direitos no sistema que está sendo testado.",
    quest: quest,
},
{
    id:3.3 ,
    assetType:"Usuários",
    securityFunction:"Proteger",
    titulo: "Proteção contas prioritárias de avaliação" ,
    description:"Use uma conta dedicada para autenticados varreduras de vulnerabilidade, que não devem ser usadas para quaisquer outras atividades administrativas e devem ser vinculado a máquinas específicas em endereços IP específicos.",
    quest: quest,
},
{
    id:3.4 ,
    assetType:"Aplicativos",
    securityFunction:"Proteger",
    titulo: "Implantação automatizada de ferramentas de gerenciamento de atualizações de sistemas operantes" ,
    description:"Implante ferramentas de atualização de software automatizadas em ordem para garantir que os sistemas operacionais estejam funcionando as atualizações de segurança mais recentes fornecidas pelo fornecedor de software.",
    quest: quest,
},
{
    id:3.5 ,
    assetType:"Aplicativos",
    securityFunction:"Proteger",
    titulo: "Implementação automatizada de ferramentas de atualização de softwares" ,
    description:"Implante ferramentas de atualização de software automatizadas em ordem para garantir que o software de terceiros em todos os sistemas está executando as atualizações de segurança mais recentes fornecido pelo fornecedor do software.",
    quest: quest,
},
{
    id:3.6 ,
    assetType:"Aplicativos",
    securityFunction:"Responder",
    titulo: "Comparação retroativa de escaneamentos de vunerabilidade" ,
    description:"Compare regularmente os resultados de varreduras de vulnerabilidade para verificar se as vulnerabilidades foram corrigidos em tempo hábil.",
    quest: quest,
},
{
    id:3.7 ,
    assetType:"Aplicativos",
    securityFunction:"Responder",
    titulo: "Utilização de processos com classificação de riscos" ,
    description:"Utilize um processo de classificação de risco para priorizar o remediação de vulnerabilidades descobertas.",
    quest: quest,
},
{
    id:4.1 ,
    assetType:"Usuários",
    securityFunction:"Proteger",
    titulo: "Manutenção de inventário de contas administrativas" ,
    description:"Use ferramentas automatizadas para inventariar todos contas administrativas, incluindo domínio e contas locais, para garantir que apenas autorizadas indivíduos têm privilégios elevados.",
    quest: quest,
},
{
    id:4.2 ,
    assetType:"Usuários",
    securityFunction:"Proteger",
    titulo: "Mudança de senhas padrão" ,
    description:"Antes de implantar qualquer novo ativo, mude todos senhas padrão para ter valores consistentes com contas de nível administrativo.",
    quest: quest,
},
{
    id:4.3 ,
    assetType:"Usuários",
    securityFunction:"Proteger",
    titulo: "Garantia de uso de contas administrativas especiais" ,
    description:"Certifique-se de que todos os usuários com conta administrativa acesso use uma conta dedicada ou secundária para atividades elevadas. Esta conta deve ser apenas usado para atividades administrativas e não Internet navegação, e-mail ou atividades semelhantes.",
    quest: quest,
},
{
    id:4.4 ,
    assetType:"Usuários",
    securityFunction:"Proteger",
    titulo: "Utilização de senhas únicas" ,
    description:"Onde a autenticação multifator não é compatível (como administrador local, root ou contas de serviço), as contas usarão senhas que são exclusivos desse sistema.",
    quest: quest,
},
{
    id:4.5 ,
    assetType:"Usuários",
    securityFunction:"Proteger",
    titulo: "Utilização de autenticação em múltiplas etapas para todas as tarefas administrativas" ,
    description:"Use autenticação multifator e criptografada canais para todos os acessos de contas administrativas.",
    quest: quest,
},
{
    id:4.6 ,
    assetType:"Usuários",
    securityFunction:"Proteger",
    titulo: "Utilização de estações de trabalho para todas as tarefas administrativas" ,
    description:"Certifique-se de que os administradores usem uma máquina dedicada para todas as tarefas administrativas ou tarefas que requerem acesso administrativo. Esta máquina será segmentado do principal da organização rede e não ter acesso à Internet. Esta máquina não será usada para ler e-mails, redigir documentos ou navegar na Internet.",
    quest: quest,
},
{
    id:4.7 ,
    assetType:"Usuários",
    securityFunction:"Proteger",
    titulo: "Acesso limitado para ferramentas de Scripting" ,
    description:"Limite o acesso a ferramentas de script (como Microsoft® PowerShell e Python) para apenas administrativo ou usuários de desenvolvimento com a necessidade de acessá-los capacidades.",
    quest: quest,
},
{
    id:4.8 ,
    assetType:"Usuários",
    securityFunction:"Detectar",
    titulo: "Relatório e alertas para mudanças nos membros do grupo administrativo" ,
    description:"Configure os sistemas para emitir uma entrada de registro e alerta quando uma conta é adicionada ou removida de qualquer privilégios administrativos atribuídos ao grupo.",
    quest: quest,
},
{
    id:4.9 ,
    assetType:"Usuários",
    securityFunction:"Detectar",
    titulo: "Relatório e alerta para tentativas mal sucedidas de login em contas administrativas" ,
    description:"Configure os sistemas para emitir uma entrada de registro e alertar sobre logins malsucedidos em uma conta administrativa.",
    quest: quest,
},
{
    id:5.1 ,
    assetType:"Aplicativos",
    securityFunction:"Proteger",
    titulo: "Estabelecimento de uma configuração segura" ,
    description:"Manter a configuração de segurança documentada padrões para todos os sistemas operacionais autorizados e software.",
    quest: quest,
},
{
    id:5.2 ,
    assetType:"Aplicativos",
    securityFunction:"Proteger",
    titulo: "Manutenção de imagens de segurança" ,
    description:"Manter imagens ou modelos seguros para todos os sistemas da empresa com base no padrões de configuração aprovados pela organização. Qualquer nova implantação de sistema ou sistema existente que fica comprometido deve ser fotografado usando uma dessas imagens ou modelos.",
    quest: quest,
},
{
    id:5.3 ,
    assetType:"Aplicativos",
    securityFunction:"Proteger",
    titulo: "Armazenamento seguro de imagens mestre " ,
    description:"Armazene as imagens mestre e modelos com segurança servidores configurados, validados com integridade ferramentas de monitoramento, para garantir que apenas as autorizadas mudanças nas imagens são possíveis.",
    quest: quest,
},
{
    id:5.4 ,
    assetType:"Aplicativos",
    securityFunction:"Proteger",
    titulo: "Implantação de ferramentas de gerenciamento de ferramentas" ,
    description:"Implantar ferramentas de gerenciamento de configuração do sistema que irá aplicar e reimplantar automaticamente definições de configuração para sistemas regularmente intervalos programados.",
    quest: quest,
},
{
    id:5.5 ,
    assetType:"Aplicativos",
    securityFunction:"Detectar",
    titulo: "Implementação automatizada de sistemas de monitoração de configurações" ,
    description:"Utilize um protocolo de automação de conteúdo de segurança (SCAP) monitoramento de configuração compatível sistema para verificar todas as configurações de segurança elementos, exceções aprovadas pelo catálogo e alerta quando ocorrem alterações não autorizadas.",
    quest: quest,
},